const capitals = {
  "aruba": "Oranjestad",
  "afghanistan": "Kabul",
  "angola": "Luanda",
  "albania": "Tirana",
  "andorra": "Andorra la Vella",
  "united arab emirates": "Abu Dhabi",
  "argentina": "Buenos Aires",
  "armenia": "Yerevan",
  "antigua and barbuda": "Saint John's",
  "australia": "Canberra",
  "austria": "Vienna",
  "azerbaijan": "Baku",
  "burundi": "Gitega",
  "belgium": "Brussels",
  "benin": "Porto-Novo",
  "burkina faso": "Ouagadougou",
  "bangladesh": "Dhaka",
  "bulgaria": "Sofia",
  "bahrain": "Manama",
  "bahamas, the": "Nassau",
  "bosnia and herzegovina": "Sarajevo",
  "belarus": "Minsk",
  "belize": "Belmopan",
  "bolivia": "Sucre",
  "brazil": "Brasília",
  "barbados": "Bridgetown",
  "brunei darussalam": "Bandar Seri Begawan",
  "bhutan": "Thimphu",
  "botswana": "Gaborone",
  "central african republic": "Bangui",
  "canada": "Ottawa",
  "switzerland": "Bern",
  "chile": "Santiago",
  "cameroon": "Yaoundé",
  "colombia": "Bogotá",
  "comoros": "Moroni",
  "cabo verde": "Praia",
  "costa rica": "San José",
  "cyprus": "Nicosia",
  "germany": "Berlin",
  "djibouti": "Djibouti",
  "dominica": "Roseau",
  "denmark": "Copenhagen",
  "dominican republic": "Santo Domingo",
  "algeria": "Algiers",
  "ecuador": "Quito",
  "spain": "Madrid",
  "estonia": "Tallinn",
  "ethiopia": "Addis Ababa",
  "finland": "Helsinki",
  "fiji": "Suva",
  "france": "Paris",
  "gabon": "Libreville",
  "united kingdom": "London",
  "georgia": "Tbilisi",
  "ghana": "Accra",
  "guinea": "Conakry",
  "gambia, the": "Banjul",
  "guinea-bissau": "Bissau",
  "equatorial guinea": "Malabo",
  "greece": "Athens",
  "grenada": "St. George's",
  "guatemala": "Guatemala City",
  "guyana": "Georgetown",
  "honduras": "Tegucigalpa",
  "croatia": "Zagreb",
  "haiti": "Port-au-Prince",
  "hungary": "Budapest",
  "indonesia": "Jakarta",
  "india": "New Delhi",
  "ireland": "Dublin",
  "iraq": "Baghdad",
  "iceland": "Reykjavik",
  "israel": "Jerusalem",
  "italy": "Rome",
  "jamaica": "Kingston",
  "jordan": "Amman",
  "japan": "Tokyo",
  "kazakhstan": "Astana",
  "kenya": "Nairobi",
  "kyrgyz republic": "Bishkek",
  "cambodia": "Phnom Penh",
  "kiribati": "South Tarawa",
  "kuwait": "Kuwait City",
  "lebanon": "Beirut",
  "liberia": "Monrovia",
  "libya": "Tripoli",
  "sri lanka": "Sri Jayawardenepura Kotte",
  "lesotho": "Maseru",
  "lithuania": "Vilnius",
  "luxembourg": "Luxembourg",
  "latvia": "Riga",
  "morocco": "Rabat",
  "moldova": "Chișinău",
  "madagascar": "Antananarivo",
  "maldives": "Malé",
  "mexico": "Mexico City",
  "marshall islands": "Majuro",
  "mali": "Bamako",
  "malta": "Valletta",
  "myanmar": "Naypyidaw",
  "montenegro": "Podgorica",
  "mongolia": "Ulaanbaatar",
  "mozambique": "Maputo",
  "mauritania": "Nouakchott",
  "mauritius": "Port Louis",
  "malawi": "Lilongwe",
  "malaysia": "Kuala Lumpur",
  "namibia": "Windhoek",
  "niger": "Niamey",
  "nigeria": "Abuja",
  "nicaragua": "Managua",
  "netherlands": "Amsterdam",
  "norway": "Oslo",
  "nepal": "Kathmandu",
  "nauru": "Yaren District",
  "new zealand": "Wellington",
  "oman": "Muscat",
  "pakistan": "Islamabad",
  "panama": "Panama City",
  "peru": "Lima",
  "philippines": "Manila",
  "palau": "Ngerulmud",
  "papua new guinea": "Port Moresby",
  "poland": "Warsaw",
  "portugal": "Lisbon",
  "paraguay": "Asunción",
  "west bank and gaza": "Ramallah",
  "qatar": "Doha",
  "romania": "Bucharest",
  "russian federation": "Moscow",
  "rwanda": "Kigali",
  "saudi arabia": "Riyadh",
  "sudan": "Khartoum",
  "senegal": "Dakar",
  "singapore": "Singapore",
  "solomon islands": "Honiara",
  "sierra leone": "Freetown",
  "el salvador": "San Salvador",
  "san marino": "San Marino",
  "somalia": "Mogadishu",
  "serbia": "Belgrade",
  "suriname": "Paramaribo",
  "slovak republic": "Bratislava",
  "slovenia": "Ljubljana",
  "sweden": "Stockholm",
  "eswatini": "Mbabane",
  "seychelles": "Victoria",
  "chad": "N'Djamena",
  "togo": "Lomé",
  "thailand": "Bangkok",
  "tajikistan": "Dushanbe",
  "turkmenistan": "Ashgabat",
  "timor-leste": "Dili",
  "tonga": "Nukuʻalofa",
  "trinidad and tobago": "Port of Spain",
  "tunisia": "Tunis",
  "tuvalu": "Funafuti",
  "tanzania": "Dodoma",
  "uganda": "Kampala",
  "ukraine": "Kyiv",
  "uruguay": "Montevideo",
  "united states": "Washington, D.C.",
  "uzbekistan": "Tashkent",
  "vanuatu": "Port Vila",
  "samoa": "Apia",
  "kosovo": "Pristina",
  "south africa": "Pretoria",
  "zambia": "Lusaka",
  "zimbabwe": "Harare"
};

export default capitals;